version: "3.3"
   
services:
  db:
    image: postgres
    env_file:
      - db.env
  web:
    image: nginx:1.19.6-alpine
    ports:
      - 8080:80
    volumes:
      - ./gah.conf:/etc/nginx/conf.d/
      - ./static:/var/www/static:ro
    depends_on:
      - geochron_at_home
  geochron_at_home:
    dockerfile: Dockerfile
    env_file:
      - production.env
    volumes:
      - ./user_upload:/code/user_upload
    depends_on:
      - db
