version: "3.3"
   
services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - "./db:/var/lib/postgresql:rw"
    env_file:
      - production.env
  web:
    image: nginx:1.19.6-alpine
    ports:
      - 3830:80
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./static:/var/www/static:ro"
    depends_on:
      - django
  django:
    build: .
    env_file:
      - production.env
    volumes:
      - "./user_upload:/code/user_upload"
    depends_on:
      - db
